### ISSUE TITLE
"Not a git repository"

### ISSUE THREAD

**Issue by lirantal** [bahmutov/ban-sensitive-files#19]
I'm working in a project which the package.json is actually inside a subfolder of the root directory where `.git` is. While `git` works just fine from inside all the folders, when running `ban` I'm getting an error: "Not a git repository"

This is probably coming from the `ggit` package and the `changed-files` function.

**Comment by bahmutov** [comment]
Hmm, probably need to update dependencies

**Comment by bahmutov** [comment]
Ok, new version https://github.com/bahmutov/ban-sensitive-files/releases/tag/v1.9.1 has been published, see if it still has problem with subfolders

**Comment by lirantal** [comment]
I think this is something that happens just on the pre-commit hook. On pre-push it's ok.

**Comment by lirantal** [comment]
@bahmutov I can still reproduce the issue on pre-commit with latest package (1.9.0)
package.json:

```
  "scripts": {
    "ban": "DEBUG=ban ban",

...

  "config": {
    "pre-git": {
      "pre-commit": [
        "yarn run ban"
      ],
...
```

**Comment by travi** [comment]
@lirantal are you still seeing this issue with the latest version. I was just added to help maintain, so might find a chance to look into it, if so.

**Comment by lirantal** [comment]
If I remember correctly I ended up moving to something else

**Comment by bahmutov** [comment]
great, closing this for now
